---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  interval: 1h0m0s
  url: https://weaveworks.github.io/tf-controller/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tf-controller
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tf-controller
      sourceRef:
        kind: HelmRepository
        name: tf-controller
  interval: 1h0m0s
  releaseName: tf-controller
  targetNamespace: default
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    allowCrossNamespaceRefs: true
    branchPlanner:
      enabled: false
    runner:
      serviceAccount:
        # -- If `true`, create a new runner service account
        create: true
        # -- Additional runner service Account annotations
        annotations: {}
        # -- Runner service account to be used
        name: ""
        # -- List of namespaces that the runner may run within
        allowedNamespaces: ["default"]
    securityContext:
      allowPrivilegeEscalation: false
      seccompProfile:
        type: RuntimeDefault
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
